# Generated by Django 5.1 on 2024-08-17 15:44

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Experience',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('company', models.CharField(max_length=255)),
                ('currently_employed', models.BooleanField(default=False)),
                ('start_date', models.DateField()),
                ('end_date', models.DateField(null=True)),
                ('role', models.CharField(max_length=255)),
                ('description', models.TextField(null=True)),
            ],
        ),
    ]
