# Generated by Django 5.1 on 2024-10-01 16:50

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('experience', '0002_alter_experience_description'),
        ('skill', '0006_alter_skill_category'),
    ]

    operations = [
        migrations.CreateModel(
            name='ExperienceSkill',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('experience', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='experience', to='experience.experience')),
                ('skill', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='skill', to='skill.skill')),
            ],
        ),
    ]
