# Generated by Django 5.1 on 2024-10-01 18:48

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('experience', '0003_experienceskill'),
        ('skill', '0006_alter_skill_category'),
    ]

    operations = [
        migrations.AlterField(
            model_name='experienceskill',
            name='experience',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='experience', to='experience.experience'),
        ),
        migrations.AlterField(
            model_name='experienceskill',
            name='skill',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='skill', to='skill.skill'),
        ),
    ]
