# Generated by Django 5.1 on 2024-09-04 11:50

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('skill', '0004_alter_category_name'),
    ]

    operations = [
        migrations.AlterField(
            model_name='skill',
            name='category',
            field=models.ForeignKey(choices=[(1, 'Technical Skills'), (2, 'Soft Skills')], on_delete=django.db.models.deletion.CASCADE, to='skill.category'),
        ),
    ]
